```{r data generation, echo=FALSE, results='hide'}
pacman::p_load(exams, tidyverse)
choices <- character(4)
explain <- character(4)

choices[1] <- "(`mean(x) - 1.96*sd(x)/sqrt(length(x)`, `mean(x) + 1.96*sd(x)/sqrt(length(x)`)"
choices[2] <-  "(`mean(x) + 1.96*sd(x)/sqrt(length(x)`, `mean(x) - 1.96*sd(x)/sqrt(length(x)`)"
choices[3] <-  "(`mean(x) - 1.96*var(x)/sqrt(length(x)`, `mean(x) + 1.96*var(x)/sqrt(length(x)`)"
choices[4] <-  "(`mean(x) - 1.64*sd(x)/sqrt(length(x)`, `mean(x) + 1.64*sd(x)/sqrt(length(x)`)"

explain[2] <- "The upper and lower bounds are reversed. The correct confidence interval formula is: mean± margin of error \n  This should have the mean(x) - margin first and mean(x) + margin second."
explain[3] <- "This option uses the variance (`var(x)`) instead of the standard deviation (`sd(x)`). Confidence intervals for the mean require the standard deviation (or standard error) of the sample, not the variance. "
explain[4] <- "1.64 is the critical value for a 90% confidence interval. For a 95% confidence interval, the appropriate critical value is 1.96. "

sol <- c(TRUE,FALSE,FALSE, FALSE)

```

Question
============
You have a numeric vector `x` in R containing sample data. Which R command correctly computes a 95% confidence interval for the population mean?

```{r questionlist, echo=FALSE, results = "asis"}
answerlist(choices, markup = "markdown")
```


Solution
=================

A confidence interval for a mean uses:
$$\bar{x} \pm z_{\alpha/2}\frac{s}{n}$$

The correct answer is

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(ifelse(sol, "TRUE", "FALSE"), explain, markup = "markdown")
```


Meta-information
================
exname: calc-CI-1-var
extype: schoice
exsolution: `r mchoice2string(sol, single = TRUE)`